name: 'dbtlastfm'
version: '1.0.0'
config-version: 2

profile: 'dbtlastfm'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  weather_station_name: "GDAŃSK-RĘBIECHOWO"
  dbt_metrics_calendar_model: d_calendar
  custom_calendar_dimension_list:
    - is_workday

models:
  # disable the default dbt_metrics calendar
  metrics:
    +enabled: false

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
