name: 'dbtlastfm'
version: '1.0.0'
config-version: 2

profile: 'dbtlastfm'

model-paths: ["models"]
seed-paths: ["seeds"]

vars:
  weather_station_name: "GDAŃSK-RĘBIECHOWO"

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
